Name: Resources and construction
IconPath: test.png
SoundPath: dekat.wav
Description: |
    Equipe de test du mode resources and construction
BrainsPackage: teams.resources_and_construction_team
AgentsBrainClasses:
    WarBase: WarBaseBrainController
    WarExplorer: WarExplorerBrainController
    WarLight: WarLightBrainController
    WarHeavy: WarHeavyBrainController
    WarRocketLauncher: WarRocketLauncherBrainController
    WarKamikaze: WarKamikazeBrainController
    WarEngineer: WarEngineerBrainController
    WarTurret: WarTurretBrainController
